<h4>This notebook will load a dataset that has finance news reports and we will convert them into chunks -> embed the chunks-> load into a vector database</h4>

In [331]:
# !pip install pinecone
# !pip install openai
# !pip install langchain
# !pip install kagglehub
# !pip install -U langchain-community
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.13.0-cp312-cp312-win_amd64.whl.metadata (12 kB)
Downloading rapidfuzz-3.13.0-cp312-cp312-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   -------------------------------- ------- 1.3/1.6 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 6.2 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.13.0

In [2]:
import kagglehub
import os
import pinecone
import openai
import pandas as pd
import numpy as np
import langchain
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Pinecone
from rapidfuzz import process

In [ ]:


# Download latest version
path = kagglehub.dataset_download("notlucasp/financial-news-headlines")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/notlucasp/financial-news-headlines?dataset_version_number=2...

100%|██████████| 3.91M/3.91M [00:01<00:00, 2.45MB/s]

Extracting files...
Path to dataset files: C:\Users\cyber\.cache\kagglehub\datasets\notlucasp\financial-news-headlines\versions\2

In [4]:
path = "C:\\Users\\cyber\\.cache\\kagglehub\\datasets\\notlucasp\\financial-news-headlines\\versions\\2"

In [5]:
df_cnbc = pd.read_csv(path + "/cnbc_headlines.csv")
df_gaurdian = pd.read_csv(path + "/guardian_headlines.csv")
df_reuters = pd.read_csv(path + "/reuters_headlines.csv")

In [31]:
df_symbols_valid = pd.read_csv("C:/Users/cyber/.cache/kagglehub/datasets/jacksoncrow/stock-market-dataset/versions/2/symbols_valid_meta.csv")

In [6]:
print(df_cnbc.describe())
print(df_gaurdian.describe())
print(df_reuters.describe())

                                                Headlines  \
count                                                2800
unique                                               2788
top     Cramer: I helped investors through the 2010 fl...
freq                                                    2

                                 Time  \
count                            2800
unique                           2474
top      8:11  PM ET Fri,  2 Nov 2018
freq                                6

                                              Description
count                                                2800
unique                                               2618
top     "Mad Money" host Jim Cramer rings the lightnin...
freq                                                  147
             Time                                          Headlines
count       17800                                              17800
unique        774                                              17795
top     25-Feb-20  Deliveroo couriers win six-figure payout in em...
freq           40                                                  2
                                                Headlines         Time  \
count                                               32770        32770
unique                                              32575          852
top     Take Five: World markets themes for the week a...  Mar 19 2020
freq                                                   12          126

                                              Description
count                                               32770
unique                                              32574
top     Following are five big themes likely to domina...
freq                                                   25

<h4>So the number of entries from all the sources are decent enough to be stored in a database</h4>

In [46]:
df_gaurdian.head()

        Time                                          Headlines
0  18-Jul-20   Johnson is asking Santa for a Christmas recovery
1  18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2  18-Jul-20  Five key areas Sunak must tackle to serve up e...
3  18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  18-Jul-20  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...

In [45]:
df_cnbc.head()

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,NaN,NaN,NaN
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."

In [47]:
df_reuters.head(5)

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...

In [50]:
print("cnbc", df_cnbc['Time'].head(), sep="\n", end="\n\n")
print("guardian", df_gaurdian['Time'].head(), sep="\n", end="\n\n")
print("reuters", df_reuters['Time'].head(), sep="\n", end="\n\n")

cnbc
0     7:51  PM ET Fri, 17 July 2020
1     7:33  PM ET Fri, 17 July 2020
2                               NaN
3     7:25  PM ET Fri, 17 July 2020
4     4:24  PM ET Fri, 17 July 2020
Name: Time, dtype: object

guardian
0    18-Jul-20
1    18-Jul-20
2    18-Jul-20
3    18-Jul-20
4    18-Jul-20
Name: Time, dtype: object

reuters
0    Jul 18 2020
1    Jul 18 2020
2    Jul 18 2020
3    Jul 18 2020
4    Jul 17 2020
Name: Time, dtype: object

<h4>So the date in the cnbc needs to be formatted to just the date as the time doesn't matter, guardian is in a different format so that's needs to be changed as well only reuters is in the correct format

In [7]:
df_reuters = df_reuters.rename(columns={"Time": "Date"})  
#convert to datetime
df_reuters['Date'] = pd.to_datetime(df_reuters['Date'])
df_reuters['Date'] = df_reuters['Date'].dt.strftime('%Y-%m-%d')
df_reuters['Date'].head(5) #check if the conversion was successful

0    2020-07-18
1    2020-07-18
2    2020-07-18
3    2020-07-18
4    2020-07-17
Name: Date, dtype: object

In [8]:
df_reuters.isnull().sum() #check for null values

Headlines      0
Date           0
Description    0
dtype: int64

So only the first 3 letters of every month, convert every month into numbers then convert to dateTime

In [9]:
df_gaurdian.dropna(how='any', inplace=True) #drop null values

In [13]:
df_gaurdian = df_gaurdian.rename(columns={"Time": "Date"})

In [14]:
df_gaurdian[df_gaurdian['Date'] == '18']

Empty DataFrame
Columns: [Date, Headlines]
Index: []

In [15]:
months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
]
new = {
    'fine' : [],
    'wrong' : []
}
df_gaurdian_date_fixed = df_gaurdian['Date'].str.split('-').apply(lambda x: f"1-{x[0]}-{x[1]}" if  x[1] not in months else f"{x[0]}-{x[1]}-{x[2]}")
print(new['wrong'], len(new['wrong']), sep="\n")

[]
0

In [16]:
df_gaurdian_date_fixed.head()

0    18-Jul-20
1    18-Jul-20
2    18-Jul-20
3    18-Jul-20
4    18-Jul-20
Name: Date, dtype: object

In [17]:
months = {
    'Jan': '01',
    'Feb': '02',
    'Mar': '03',
    'Apr': '04',
    'May': '05',
    'Jun': '06',
    'Jul': '07',
    'Aug': '08',
    'Sep': '09',
    'Oct': '10',
    'Nov': '11',
    'Dec': '12'
}

df_gaurdian_temp = df_gaurdian_date_fixed.str.split('-').apply(lambda x:f"20{x[2]}-{months[x[1]]}-{x[0]}" )

df_gaurdian_temp.head(5) #check if the conversion was successful

0    2020-07-18
1    2020-07-18
2    2020-07-18
3    2020-07-18
4    2020-07-18
Name: Date, dtype: object

In [18]:
df_gaurdian['Date'] = df_gaurdian_temp

In [19]:
df_gaurdian.head()

         Date                                          Headlines
0  2020-07-18   Johnson is asking Santa for a Christmas recovery
1  2020-07-18  ‘I now fear the worst’: four grim tales of wor...
2  2020-07-18  Five key areas Sunak must tackle to serve up e...
3  2020-07-18  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  2020-07-18  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...

In [20]:
df_cnbc['Time'].describe()
df_cnbc['Time'].isnull().sum()
#Get rows where time is null and headlines is not null
df_cnbc[df_cnbc['Time'].isnull() & df_cnbc['Headlines'].notnull()]
#drop these rows
df_cnbc.dropna(subset=['Time'], inplace=True) #drop null values
df_cnbc['Time'].isnull().sum() #check if the conversion was successful

0

In [21]:
df_cnbc_temp = df_cnbc['Time'].str.split(',').apply(lambda x: x[1].lstrip() )
# df_cnbc_temp = df_cnbc_temp.str.split(',').apply(lambda x:f"20{x[2]}-{months[x[1]]}-{x[0]}")
df_cnbc_temp.head(5)

0    17 July 2020
1    17 July 2020
3    17 July 2020
4    17 July 2020
5    16 July 2020
Name: Time, dtype: object

In [22]:
months = [
    'Jan', 'Feb', 'March', 'April', 'May', 'June',
    'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'
]
new = {
    'fine' : [],
    'wrong' : []
}
df_cnbc_date_fixed = df_cnbc_temp.str.split(' ').apply(lambda x: f"{x[2]}-{x[1]}-{x[0]}")
df_cnbc_date_fixed.head(5) #check if the conversion was successful

0    2020-July-17
1    2020-July-17
3    2020-July-17
4    2020-July-17
5    2020-July-16
Name: Time, dtype: object

In [23]:
print(new['fine'][:5], len(new['fine']), sep="\n", end="\n\n")

[]
0

In [24]:
months = {
    'Jan': '01',
    'Feb': '02',
    'March': '03',
    'April': '04',
    'May': '05',
    'June': '06',
    'July': '07',
    'Aug': '08',
    'Sept': '09',
    'Oct': '10',
    'Nov': '11',
    'Dec': '12'
}

df_cnbc_temp = df_cnbc_date_fixed.str.split('-').apply(lambda x:f"{x[0]}-{months[x[1]]}-{x[2]}" )

df_cnbc_temp.head(5) #check if the conversion was successful

0    2020-07-17
1    2020-07-17
3    2020-07-17
4    2020-07-17
5    2020-07-16
Name: Time, dtype: object

In [25]:
df_cnbc['Date'] = df_cnbc_temp
df_cnbc.drop(columns=['Time'], inplace=True) #drop the old time column

In [26]:
#convert to datetime
df_cnbc['Date'] = pd.to_datetime(df_cnbc['Date'])
df_cnbc['Date'] = df_cnbc['Date'].dt.strftime('%Y-%m-%d')
df_cnbc['Date'].head(5) #check if the conversion was successful

0    2020-07-17
1    2020-07-17
3    2020-07-17
4    2020-07-17
5    2020-07-16
Name: Date, dtype: object

In [27]:
df_gaurdian['Date'] = pd.to_datetime(df_gaurdian['Date'])
df_gaurdian['Date'] = df_gaurdian['Date'].dt.strftime('%Y-%m-%d')

In [28]:
df_cnbc.sort_values(by='Date', inplace=True)
df_gaurdian.sort_values(by='Date', inplace=True)    
df_reuters.sort_values(by='Date', inplace=True)

In [29]:
df_reuters['Date'].head(5)

32769    2018-03-20
32738    2018-03-20
32737    2018-03-20
32736    2018-03-20
32735    2018-03-20
Name: Date, dtype: object

<h4> Now we need to add a "Ticker" Coloumn so that it becomes easy for the vector db to fetch the data later</h4>

In [32]:
df_symbols_valid.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [33]:
df_symbols_valid_temp = df_symbols_valid[df_symbols_valid['ETF'] == 'N'] #filter out ETFs

In [34]:
df_symbols_valid_temp = df_symbols_valid_temp[['Symbol', 'Security Name']].copy() #keep only the relevant columns

In [39]:
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('Common Stock', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('Depositary Shares', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('Units', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('Limited', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('Ordinary Shares', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('technologies', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('corporation', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('inc', '') #remove common stock from the security name
df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.replace('group', '') #remove common stock from the security name

df_symbols_valid_temp['Security Name'] = df_symbols_valid_temp['Security Name'].str.lower()

In [40]:
df_symbols_valid_temp

     Symbol                                      Security Name
0         A                                       agilent , .
1        AA                                           alcoa
3      AACG  ata creativity global - american , each repres...
5       AAL                           american airlines , . -
6      AAMC               altisource asset management corp com
...     ...                                                ...
8044    ZUO                                  zuora, . class a
8045    ZVO                                         zovio . -
8046   ZYME                          zymeworks . common shares
8047   ZYNE                      zynerba pharmaceuticals, . -
8048   ZYXI                                        zynex, . -

[5884 rows x 2 columns]

In [44]:
i =0 
symbolAndSecurityName = {
}
for j, symbol_row in df_symbols_valid_temp.iterrows():
    symbolAndSecurityName[f"{symbol_row['Symbol']}"] = []
    symbolAndSecurityName[f"{symbol_row['Symbol']}"].append(symbol_row['Security Name'])

symbolAndSecurityName['MSFT']

['microsoft  - ']

In [47]:
for i in symbolAndSecurityName.values():
    print(i)
    i[0] = i[0].replace(' ', '')

['agilent , . ']
['alcoa   ']
['ata creativity global - american , each representing two common shares']
['american airlines , . - ']
['altisource asset management corp com']
['atlantic american  - ']
["aaron's, . "]
['applied optoelectronics, . - ']
['aaon, . - ']
['advance auto parts  advance auto parts  w/i']
['apple . - ']
['american assets trust, . ']
['almaden minerals, ltd. common shares']
['atlas air worldwide holdings - ']
['axon enterprise, . - ']
['alliancebernstein holding l.p.  ']
['abb ltd ']
['abbvie . ']
['amerisourcebergen  ']
['ameris bancorp - ']
['abeona therapeutics . - ']
['ambev s.a. american  (each representing 1 common share)']
['asbury automotive   ']
['arca biopharma, . - ']
['abm industries orporated ']
['abiomed, . - ']
['arbor realty trust ']
['abbott laboratories ']
['allegiance bancshares, . - ']
['arbutus biopharma  - ']
['associated capital , . ']
['arcosa, .  ']
['acadia pharmaceuticals . - ']
['acamar partners acquisition corp. - class a ']
['acamar partners acquisition corp. - ']
['aurora cannabis . common shares']
['atlantic capital bancshares, . - ']
['american campus communities  ']
['acco brands  ']
['accel entertainment, . ']
['acer therapeutics . - ']
['arch capital  ltd. - ']
['arch capital  ltd. -  each representing 1/1,000th interest in a share of5.45% non-cumulative preferred shares, series f']
['arch capital  ltd. -  representing interest in 5.25% non-cumulative preferred series e shrs']
['aluminum  of china  american ']
['acadia healthcare company, . - ']
['achieve life sciences, .  - common shares']
['acacia communications, . - ']
['ac immune sa - ']
['aci worldwide, . - ']
['axcelis , . - ']
['aecom ']
['acm research, . - class a ']
['accenture plc class a  (ireland)']
['acnb  - ']
['acorda therapeutics, . - ']
['aberdeen ome credit strategies fund common shares']
['ares commercial real estate  ']
['aclaris therapeutics, . - ']
['acelrx pharmaceuticals, . - ']
['acasti pharma, . - class a ']
['acacia research  - ']
['act ii global acquisition corp. - class a ']
['act ii global acquisition corp. - unit']
['acme united . ']
['allianzgi diversified ome & convertible fund common shares of beneficial interest']
['aerocentury corp. ']
['adaptimmune therapeutics plc - american ']
['adobe . - ']
['agree realty  ']
['advanced emissions solutions, . - ']
['analog devices, . - ']
['adial pharmaceuticals,  - ']
['archer-daniels-midland company ']
['adma biologics  - ']
['adamis pharmaceuticals  - ']
['adamas pharmaceuticals, . - ']
['adient plc  ']
['automatic data processing, . - ']
['adaptive bio  - ']
['aduro biotech, . - ']
['alliance data systems  ']
['autodesk, . - ']
['advanced disposal services, . ']
['adt . ']
['adtran, . - ']
['addus homecare  - ']
['adverum bio, . - ']
['adams diversified equity fund .']
['addex therapeutics ltd - american ']
['advaxis, . - ']
['adams resources & energy, . ']
['aegon n.v. perp. cap. secs. floating rate (netherlands)']
['ameren  ']
['aberdeen emerging markets equity ome fund, . ']
['aegon funding company llc 5.10% subordinated notes due 2049']
['aegon n.v. ']
['aegion corp - class a ']
['aehr test systems - ']
['advanced energy industries, . - ']
['american equity investment life holding company ']
['agnico eagle mines  ']
['aethlon medical, . - ']
['american eagle outfitters, . ']
['american electric power company, . ']
['aercap holdings n.v. ']
['aerie pharmaceuticals, . - ']
['the aes  ']
['allied esports entertainment, . - ']
['addvantage  , . - ']
['audioeye, . - ']
['aeterna zentaris . - ']
['alliancebernstein national municipal ome fund ']
['allied capital  allied capital  6.875% notes due april 15, 2047']
['american financial , . ']
['american financial , . 5.125% subordinated debentures due 2059']
['american financial , . 6% subordinated debentures due 2055']
['atlas financial holdings, . - ']
['armstrong flooring, . ']
['american finance trust, . - class a ']
['american finance trust, . - 7.50% series a cumulative redeemable perpetual preferred stock']
['aflac orporated ']
['affimed n.v. - ']
['apollo senior floating rate fund . ']
['afya  - class a common shares']
['first majestic silver corp.  (canada)']
['agba acquisition  - ordinary share']
['agba acquisition  - unit']
['agco  ']
['aberdeen global dynamic dividend fund']
['agex therapeutics, . ']
['agenus . - ']
['agrofresh solutions, . - ']
['alamos gold . class a common shares']
['agios pharmaceuticals, . - ']
['aeglea biotherapeutics, . - ']
['federal agricultural mortgage  ']
['federal agricultural mortgage  5.875% non-cumulative preferred stock, series a']
['agm  holdings . - class a ']
['allergan plc ']
['agnc investment corp. - ']
['agnc investment corp. -  rep 6.875% series d fixed-to-floating cumulative redeemable preferred stock']
['agnc investment corp. -  each representing a 1/1,000th interest in a share of 7.00% series c fixed-to-floating rate cumulative redeemable preferred stock']
['agnc investment corp. - , each representing a 1/1,000th interest in a share of series e fixed-to-floating cumulative redeemable preferred stock']
['agnc investment corp. -  each representing a 1/1,000th interest in a share of 6.125% series f fixed-to-floating rate cumulative redeemable preferred stock']
['assured guaranty ltd. ']
['avangrid, . ']
['adecoagro s.a. common shares']
['agile therapeutics, . - ']
['playags, . ']
['applied genetic   - ']
['argan, . ']
['agilysys, . - ']
['a.h. belo  (tx) ']
['adapthealth corp.  - class a ']
['armada hoffler properties, . ']
['allied healthcare products, . - ']
['ashford hospitality trust  ']
['arlington asset investment corp class a (new)']
['arlington asset investment corp 6.750% notes due 2025']
['apollo tactical ome fund . ']
['american international , . new ']
['aesthetic medical international holdings  ltd. - american ']
['senmiao technology  - ']
['aikido pharma . - ']
['aim immunotech . ']
['altra industrial motion corp. - ']
['aimmune therapeutics, . - ']
['albany international  ']
['ashford . (holding company) ']
['apollo investment  - closed end fund']
['allianzgi artificial intelligence & technology opportunities fund common shares']
['aar corp. ']
['airgain, . - ']
['air industries  ']
['air t, . - ']
['air t, . - trust preferred securities']
['applied industrial , . ']
['apartment investment and management company ']
['arlington asset investment corp 6.625% notes due 2023']
['assurant, . ']
['assurant, . 6.50% series d mandatory convertible preferred stock, $1.00 par value']
['arthur j. gallagher & co. ']
['aerojet rocketdyne holdings, . ']
['great ajax corp. ']
['great ajax corp. 7.25% convertible senior notes due 2024']
['akamai , . - ']
['akebia therapeutics, . - ']
['akcea therapeutics, . - ']
['akers biosciences . - ']
['asanko gold .']
['acadia realty trust ']
['akero therapeutics, . - ']
['akorn, . - ']
['akoustis , . - ']
['akari therapeutics plc - american ']
['air lease  class a ']
['alberton acquisition  - ']
['alberton acquisition  - rights']
['alberton acquisition  - unit']
['albemarle  ']
['albireo pharma, . - ']
['alcon . ']
['alico, . - ']
['aldeyra therapeutics, . - ']
['allete, .']
['alector, . - ']
['alexander & baldwin, .  reit holding company']
['alamo , . ']
['align technology, . - ']
['allegro merger corp. - ']
['allegro merger corp. - unit']
['allegiant travel company - ']
['alimera sciences, . - ']
['alj regional holdings, . - ']
['alaska air , . ']
['alkermes plc - ']
['allstate  (the) ']
['allegion plc ']
['allakos . - ']
['allogene therapeutics, . - ']
['allot ltd. - ']
['ally financial . ']
['allena pharmaceuticals, . - ']
['alnylam pharmaceuticals, . - ']
['alio gold . common shares (canada)']
['astronova, . - ']
['alpine immune sciences, . - ']
['alarm.com holdings, . - ']
['aileron therapeutics, . - ']
['alerus financial  - ']
['alaska communications systems , . - ']
['allison transmission holdings, . ']
['altimmune, . - ']
['alta equipment  . class a ']
['altus midstream company - class a ']
['altair engineering . - class a ']
['alussa energy acquisition corp. class a ']
['autoliv, . ']
["alexander's, . "]
['alexion pharmaceuticals, . - ']
['alithya  . - class a subordinate voting shares']
['antero midstream  ']
['amag pharmaceuticals, . - ']
['amalgamated bank - class a ']
['applied materials, . - ']
['ambarella, . - ']
['ambac financial , . ']
['ambow education holding ltd. american depository shares, each representing two class a ordinary shares']
['amc entertainment holdings, . class a ']
['amci acquisition corp. - class a ']
['amci acquisition corp. - unit']
['amcor plc ']
['amc networks . - class a ']
['advanced micro devices, . - ']
['ametek, .']
['amedisys  - ']
['apollo medical holdings, . - ']
['affiliated managers , . ']
['amgen . - ']
['american homes 4 rent common shares of beneficial interest']
['amplitude healthcare acquisition  - class a ']
['amplitude healthcare acquisition  - unit']
['jpmorgan chase capital xvi jp morgan alerian mlp etn']
['assetmark financial holdings, . ']
['amkor technology, . - ']
['amn healthcare services  amn healthcare services ']
['american national bankshares, . - ']
['allied motion , . - ']
['america movil, s.a.b. de c.v. class a american ']
['ameriprise financial, . ']
['ampio pharmaceuticals, .']
['amphastar pharmaceuticals, . - ']
['amplify energy corp. ']
['american river bankshares - ']
['ameresco, . class a ']
['ameri holdings, . - ']
['a-mark precious metals, . - ']
['amarin  plc - american , each representing one ordinary share']
['amyris, . - ']
['amneal pharmaceuticals, . class a ']
['american shared hospital services ']
['american superconductor  - ']
['amerisafe, . - ']
['american software, . - class a ']
['american tower  (reit) ']
['amerant bancorp . - class a ']
['amerant bancorp . - class b ']
['td ameritrade holding  - ']
['aemetis,  - ']
['etracs alerian mlp index etn']
['etracs alerian mlp index etn series b due july 18, 2042']
['american woodmark  - ']
['america movil, s.a.b. de c.v. american depository receipt series l']
['amazon.com, . - ']
['autonation, . ']
['anaptysbio, . - ']
['american national insurance company - ']
['anchiano therapeutics ltd. - american ']
['andina acquisition corp. iii - ']
['andina acquisition corp. iii - unit']
['the andersons, . - ']
['arista networks, . ']
['abercrombie & fitch company ']
['angi homeservices . - class a ']
['angiodynamics, . - ']
['anworth mortgage asset  ']
['anika therapeutics . - ']
['ani pharmaceuticals, . - ']
['anixa biosciences, . - ']
['anpac bio-medical science co., ltd. - american ']
['ansys, . - ']
['airnet technology . - american , each representing ten ordinary shares']
['anthem, . ']
['annovis bio, . ']
['sphere 3d corp. - common shares']
['american outdoor brands  - ']
['aberdeen total dynamic dividend fund ']
['aon plc class a  (ireland)']
['a.o. smith  ']
['alpha and omega semiconductor  - common shares']
['ampco-pittsburgh  ']
['apache  ']
['artisan partners asset management . class a ']
['air products and chemicals, . ']
['applied dna sciences, . - ']
['american public education, . - ']
['apollo endosurgery, . - ']
['apex global brands . - ']
['amphenol  ']
['aphria . common shares']
['apple hospitality reit, . common shares']
['apellis pharmaceuticals, . - ']
['applied therapeutics, . - ']
['aptorum   - class a ']
['apollo global management, . class a ']
['apogee enterprises, . - ']
['cellect biotechnology ltd. - american ']
['appfolio, . - class a ']
['appian  - class a ']
['digital turbine, . - ']
['aprea therapeutics, . - ']
['blue apron holdings, . class a ']
['alpha pro tech, ltd. ']
['aptose biosciences, . - common shares']
['preferred apartment communities, . ']
['aptiv plc ']
['aptinyx . - ']
['aptevo therapeutics . - ']
['asia pacific wire & cable   - common shares, par value .01 per share']
['apex technology acquisition  - class a ']
['apex technology acquisition  - unit']
['apergy   ']
['apyx medical  - ']
['aquabounty , . - ']
['aqua metals, . - ']
['algonquin power & utilities corp. common shares']
['algonquin power & utilities corp. 6.875% fixed-to-floating rate subordinated notes series 2018-a due october 17, 2078']
['algonquin power & utilities corp. 6.20% fixed-to-floating subordinated notes series 2019-a due july 1, 2079']
['aquestive therapeutics, . - ']
['evoqua water  corp. ']
['antero resources  ']
['american renal associates holdings,  ']
['aravive, . - ']
['accuray orporated - ']
['arc document solutions, . ']
['arcbest  - ']
['ares capital  - closed end fund']
['arco platform  - class a common shares']
['arch coal, . class a ']
['arcos dorados holdings . class a shares']
['arcturus therapeutics holdings . - ']
['ardagh  s.a. common shares']
['ares dynamic credit allocation fund, . common shares']
['aridis pharmaceuticals . - ']
['ardelyx, . - ']
['alexandria real estate equities, . ']
['american resources  - class a ']
['ares management  class a ']
['argo  international holdings, ltd. 6.5% senior notes due 2042']
['argo  international holdings, ltd.']
['argenx se - american ']
['apollo commercial real estate finance, ']
['ark restaurants corp. - ']
['american realty investors, . ']
['arlo , . ']
['alliance resource partners, l.p. - common  representing  partnership interests']
['aramark ']
['armata pharmaceuticals, . ']
['arena pharmaceuticals, . - ']
['arconic   ']
['archrock, . ']
['arrow financial  - ']
['aerpio pharmaceuticals, . - ']
['arcutis biotherapeutics, . - common stock']
['armour residential reit, .']
['artelo biosciences, . - ']
['artesian resources  - class a non-voting ']
["art's-way manufacturing co., . - "]
['arvinas, . - ']
['arrow electronics, . ']
['arrowhead pharmaceuticals, . - ']
['arya sciences acquisition corp. - class a ']
['arya sciences acquisition corp. - unit']
['asa  gold and precious metals ']
['associated banc-corp ']
['ardmore shipping  ']
['asta funding, . - ']
['liberty all-star growth fund, .']
['asgn orporated ']
['ashland global holdings . ']
['advansix .  ']
['aslan pharmaceuticals  - american ']
['avino silver & gold mines ltd. common shares (canada)']
['assembly biosciences, . - ']
['asml holding n.v. - new york registry shares']
['ascena retail , . - ']
['ascendis pharma a/s - american ']
['aspen aerogels, . ']
['altisource portfolio solutions s.a. - ']
['aspen  . - ']
['grupo aeroportuario del sureste, s.a. de c.v. ']
['assertio therapeutics, . - ']
['ameriserv financial . - ']
['ameriserv financial . - ameriserv financial trust i - 8.45% beneficial unsecured securities, series a']
['astrotech  - ']
['astec industries, . - ']
['asure software  - ']
['ase technology holding co., ltd. american  (each representing two common shares) ']
['amtech systems, . - ']
['atlantic power   (canada)']
['america first multifamily investors, l.p. - beneficial unit certificates (bucs) representing  partnership interests']
['atlas corp. common shares']
['atlas technical consultants, . - class a ']
['alphatec holdings, . - ']
['a10 networks, . ']
['anterix . - ']
['adtalem global education . ']
['athene holding ltd. class a common shares']
['alterity therapeutics  - american ']
['autohome . american , each representing one class a ordinary share.']
['athersys, . - ']
['allegheny  orporated ']
['atif holdings  - ']
['atkore international  . ']
['atlanticus holdings  - ']
['ames national  - ']
['ipath select mlp etn']
['atn international, . - ']
['actinium pharmaceuticals, . (delaware) ']
['athenex, . - ']
['atmos energy  ']
['atomera orporated - ']
['atossa therapeutics, . - ']
['aptar, . ']
['atara biotherapeutics, . - ']
['atricure, . - ']
['atrion  - ']
['astronics  - ']
['antares pharma, . - ']
['air transport services ,  - ']
['atento s.a. ']
['altice usa, . class a ']
['acorn international, . ads']
['activision blizzard,  - ']
['avenue therapeutics, . - ']
['anglogold ashanti  ']
['atlantic union bankshares  - ']
['auburn national ban, . - ']
['audiocodes ltd. - ']
['auryn resources . common shares']
['golden minerals company ']
['aurinia pharmaceuticals  - common shares']
['autolus therapeutics plc - american ']
['autoweb, . - ']
['yamana gold .  (canada)']
['avista  ']
['grupo aval acciones y valores s.a. adr (each representing 20 preferred shares)']
['aerovironment, . - ']
['avalonbay communities, . ']
['avalon globocare corp. - ']
['american vanguard   ($0.10 par value)']
['avadel pharmaceuticals plc - american  each representing one ordinary share']
['aveo pharmaceuticals, . - ']
['broadcom . - ']
['broadcom . - 8.00% mandatory convertible preferred stock, series a']
['avinger, . - ']
['avianca holdings s.a. american  (each representing 8 preferred shares)']
['avid technology, . - ']
['advent convertible and ome fund']
['avalara, . ']
['avanos medical, . ']
['aviat networks, . - ']
['avrobio, . - ']
['avnet, . - ']
['avantor, . ']
['anavex life sciences corp. - ']
['avery dennison  ']
['avaya holdings corp. ']
['alliancebernstein global high ome fund']
['armstrong world industries  ']
['american water works company, . ']
['aberdeen global premier properties fund common shares of beneficial interest']
['american states water company ']
['aware, . - ']
['avalon holdings  ']
['axos financial, . ']
['abraxas petroleum  - ']
['accelerate diagnostics, . - ']
['anixter international . ']
['axogen, . - ']
['axovant gene therapies ltd. - common shares']
['american axle & manufacturing holdings, . ']
['axcella health . - ']
['axonics modulation , . - ']
['axos financial, . 6.25% subordinated notes due 2026']
['american express company ']
['amrep  ']
['axis capital holdings  ']
['axsome therapeutics, . - ']
['axalta coating systems ltd. common shares']
['axt  - ']
['alexco resource corp common shares (canada)']
['atlantica yield plc - ']
['acuity brands, . ']
['aytu bioscience, . - ']
['alteryx, . class a ']
['astrazeneca plc ']
['autozone, . ']
['aspen technology, . - ']
['azure power global  equity shares']
['azurrx biopharma, . - ']
['azul s.a. american  (each representing three preferred shares)']
['azz .']
['barnes , . ']
['boeing company (the) ']
['alibaba  holding  american  each representing eight ordinary share']
['bank of america  ']
['blackrock municipal ome investment quality trust']
['booz allen hamilton holding  ']
['braskem sa adr']
['ipatha series b bloomberg cotton subindex total return etn']
['brookfield asset management . ']
['banc of california, . ']
['bandwidth . - class a ']
['bancfirst  - ']
['bancfirst  - 7.2% cumulative trust preferred securities']
['banner  - ']
['stonecastle financial corp - ']
['credicorp ltd. ']
['graniteshares gold trust shares of beneficial interest']
['bioanalytical systems, . - ']
['battalion oil  ']
['liberty media  - series a liberty braves ']
['liberty media  - series c liberty braves ']
['baxter international . ']
['blackberry  ']
['banco bbva argentina s.a. ads']
['bed bath & beyond . - ']
['concrete pumping holdings, .  - ']
['banco bradesco sa american ']
['barings bdc, . ']
['banco bradesco sa american  (each representing one common share)']
['blackrock municipal ome investment trust']
['beasley broadcast , . - class a ']
['brickell biotech, . - ']
['bridgebio pharma, . - ']
['blackrock municipal bond trust']
['bhp  plcsponsored adr']
['blackrock taxable municipal bond trust common shares of beneficial interest']
['bbq holdings, .  - ']
['barrett business services, . - ']
['brookfield business partners l.p.  partnership  ']
['banco bilbao vizcaya argentaria s.a. ']
['build-a-bear workshop, . ']
['bbx capital  class a ']
['best buy co., . ']
['brunswick  ']
['bcb bancorp, . (nj) - ']
['boise cascade, l.l.c. ']
['biocardia, . - ']
['bce, . ']
['bonanza creek energy, . ']
['atreca, . - class a ']
['banco de chile banco de chile ads']
['brainstorm cell therapeutics . - ']
['ipath pure beta broad commodity etn']
['baycom corp - ']
['brinks company (the) ']
['b communications ltd. - ']
['blucora, . - ']
['brightcove . - ']
['1895 bancorp of wisconsin, . - ']
['balchem  - ']
['biocryst pharmaceuticals, . - ']
['barclays plc ']

In [65]:
df_reuters['Description'][1]

'Walt Disney  has become the latest company to slash its advertising spending on Facebook Inc  as the social media giant faces an ad boycott over its handling of hate speech and controversial content, the Wall Street Journal reported on Saturday, citing people familiar with the situation.'